spring:
  application:
    name: nyayassist

  main:
    web-application-type: servlet
    banner-mode: off

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2:3b

    mcp:
      server:
        name: lawyer-assistant
        version: 1.0.0
        type: SYNC

logging:
  level:
    root: INFO
    org.springframework.ai: DEBUG